mysql:
  image: mysql
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "docker"
    MYSQL_DATABASE: "docker"
  restart: always

proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    DEFAULT_HOST: yourdomain.com
  ports:
    - "80:80"
  restart: always

backend:
  image: julienvincent/laravel
  ports:
    - "8080:80"
  expose:
    - "80"
  volumes:
     - ./backend/src:/data/www
  environment:
    VIRTUAL_HOST: api.yourdomain.com
  links:
    - mysql
  restart: always

frontend:
  image: node
  ports:
    - "8000:8000"
    - "4200:4200"
  expose:
    - "80"
  volumes:
    - ./frontend/src/:/serve
    - ./node_modules/:/node_modules
  environment:
    VIRTUAL_HOST: www.yourdomain.com,yourdomain.com
  working_dir: /serve
  command: node serve.js
  restart: always

composer:
  image: julienvincent/composer
  volumes:
    - ./backend/src:/data/www
  working_dir: /data/www

artisan:
  image: julienvincent/artisan
  volumes:
    - ./backend/src:/data/www
  working_dir: /data/www
  links:
    - mysql